### ISSUE TITLE
Issue in lesson 31 (configuring qaurkus demo)

### ISSUE THREAD

**Issue by ntrmsrc** [agoncal/agoncal-course-quarkus-starting#4]
Hi!
I'm in lession 31 and trying to open the config editor (http://localhost:8080/q/dev/) as in the demo.

But ... I get an internal server error.
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.calculate(ConfigDescriptionsManager.java:100)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.values(ConfigDescriptionsManager.java:59)

In the console I see:
2022-09-19 20:47:07,086 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-35) Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

Looking on the web, I saw a solution that didn't work for me (https://github.com/konveyor/tackle-pathfinder/issues/190 It looked like the same issue except in the solution the "io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider" was { }).

I'm on an Apple M1. Using Java SE 17.0.4.1, GraalVM EE 22.2.0 and Apache Maven 3.8.6.

Please advice.

**Comment by ntrmsrc** [comment]
Solved it.

Used the previously mentioned solution but updated the classifier to the M1 chip (duh ;-) )
 
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-resolver-dns-native-macos</artifactId>
      <version>4.1.82.Final</version>
      <classifier>osx-aarch_64</classifier>
    </dependency>
